import { chromium } from 'playwright'
const browser = await chromium.launch({ channel: 'chromium' })
const page = await browser.newPage({ viewport: { width: 1440, height: 950 } })
const errors = []
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message))
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto('http://localhost:5174/app/bounties', { waitUntil: 'networkidle' })
await page.waitForTimeout(6000)
console.log('rows:', await page.locator('main button').filter({ hasText: /GEN/ }).count())
await page.getByRole('button', { name: /Connect wallet/i }).first().click()
await page.waitForTimeout(800)
await page.getByRole('button', { name: /Connect browser wallet/i }).click()
await page.waitForTimeout(2500)
await page.getByRole('button', { name: /No injected wallet|Connect browser wallet/i }).count()
console.log('no-injected-wallet notice shown:', (await page.getByText(/No injected wallet detected/i).count()) > 0)
await page.screenshot({ path: 'shot-final-modal.png' })
console.log('console errors:', errors.length)
for (const e of errors.slice(0, 5)) console.log(' !', e.slice(0, 160))
await browser.close()